### ISSUE TITLE
JavaScript 面向对象编程（一）—— 创建对象 | Deepspace

### ISSUE THREAD

**Issue by IDeepspace** [IDeepspace/IDeepspace.github.io#37]
https://togoblog.cn/javascript-object-oriented-programming-1/ 

 一、万物皆对象JavaScript 的所有数据（非基本类型数据）都可以看成对象，所以我们常说 JavaScript 中万物皆对象（虽然并不完全正确）。 在 JavaScript 中，对象是一个泛化的概念，任何值都可以转换为对象，以对象的方式进行使用。如数字对象、布尔值对象、字符串对象、函数对象、数组对象等等，它们都继承 Object 类型对象。同时，JavaScript 也允许自定义对象。 面向

**Comment by chuttin** [comment]
星星真棒

**Comment by MaeveQIU** [comment]
星星真棒！👍🏻

**Comment by xiy037** [comment]
星星真棒

**Comment by UI-Mario** [comment]
xxnb:kissing::kissing::kissing:

**Comment by MargotGuo** [comment]
星星真棒！!!

**Comment by IDeepspace** [comment]
> @MargotGuo
> 星星真棒！!!

果果真棒
