### ISSUE TITLE
JavaScript 中的原型和原型链 | Deepspace

### ISSUE THREAD

**Issue by IDeepspace** [IDeepspace/IDeepspace.github.io#39]
https://togoblog.cn/javascript-prototypes-and-prototype-chains/ 

 JavaScript 中的原型和原型链一、通过 new 创建对象我们知道，使用 new 操作符可以创建并初始化一个新对象。关键字 new 后跟随一个函数调用，这里的函数称为构造函数（constructor）。 const person = new Object();  person.name = 'Deepspace'; person.age = 23; person.job = 'Softwar

**Comment by xiy037** [comment]
星星真棒
